content:
  - name: liturgy
    label: Liturgy
    folder: liturgy
    extension: md
    create: true

    filename:
      template: "{{slug}}"

  - name: date
    label: Date
    type: date
    required: true

  - name: order
    label: Order
    type: number

  - name: show
    label: Show
    type: boolean
    default: true

  - name: excerpt
    label: Excerpt
    type: text

  - name: body
    label: Content
    type: markdown
