content:
  - name: liturgy
    label: Liturgy
    folder: liturgy
    type: collection
    path: liturgy
    extension: md
    create: true
    fields:
      - name: date
        label: Date
        type: date
        required: true

      - name: title
        label: Title
        type: string
        required: true

      - name: order
        label: Order
        type: number

      - name: show
        label: Show
        type: boolean
        default: true

      - name: excerpt
        label: Excerpt
        type: text

      - name: body
        label: Content
        type: markdown
media:
  - name: files
    label: Files
    input: files/documents
    output: /files/documents
    categories: [document]
  - name: images # Note: 'name' key is required here
    label: Images
    input: images
    output: /images
    extensions: [png, webp, jpg, jpeg]
