content:
  - name: liturgy
    label: Liturgy
    folder: liturgy
    type: collection
    extension: md
    create: true
    fields:
      - name: date
        label: Date
        type: date
        required: true

      - name: order
        label: Order
        type: number

      - name: show
        label: Show
        type: boolean
        default: true

      - name: excerpt
        label: Excerpt
        type: text

      - name: body
        label: Content
        type: markdown
