content:
  - name: pages
    label: Posts
    path: posts
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true

      - name: slug
        label: Slug
        type: text
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: order
        label: Order
        type: number
        required: true

      - name: show
        label: Show
        type: boolean
        default: true

      - name: excerpt
        label: Excerpt
        type: textarea

      - name: body
        label: Content
        type: markdown
