collections:
  - name: posts
    label: Pages
    folder: posts
    extension: md
    create: false

    filename:
      template: "{{slug}}"

    fields:
      - name: title
        label: Title
        type: text
        required: true

      - name: slug
        label: Slug
        type: text
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: order
        label: Order
        type: number

      - name: show
        label: Show
        type: boolean
        default: true

      - name: excerpt
        label: Excerpt
        type: text

      - name: body
        label: Content
        type: markdown
